### ISSUE TITLE
Linked Window example sometimes throws exception and has wrong Sketch2 size window

### ISSUE THREAD

**Issue by GoogleCodeExporter** [gicentre/gicentreutils#15]
```
From http://www.gicentre.net/utils/multiwindow/ the linked window example


What steps will reproduce the problem?
1. place sketch code in tab
2. place sketch2 code in seperate tab
3. Run the example
------------------------------
What is the expected output? What do you see instead?
Expected Sketch2 wondow size to be 300x300 but result is a window of size 
116x62.

In addition somethings the following exception occurs:

java.lang.IllegalArgumentException: Width (116) and height (0) cannot be <= 0
	at java.awt.image.DirectColorModel.createCompatibleWritableRaster(Unknown Source)
	at java.awt.GraphicsConfiguration.createCompatibleImage(Unknown Source)
	at processing.core.PGraphicsJava2D.allocate(PGraphicsJava2D.java:198)
	at processing.core.PGraphicsJava2D.setSize(PGraphicsJava2D.java:132)
	at processing.core.PApplet.resizeRenderer(PApplet.java:1654)
	at processing.core.PApplet.run(PApplet.java:2250)
	at java.lang.Thread.run(Unknown Source)
-----------------------
What version of the product are you using? On what operating system?
Version: 3.3
Windows-7 64-bit with 32-bit processing installed.
-----------------------
Please provide any additional information below.
Sommetimes get same exception running the "Embedding sketches in a single 
window" Hello World! example as well.


```

Original issue reported on code.google.com by `jas0...@hotmail.com` on 2 Jun 2014 at 4:03

**Comment by jwoLondon** [comment]
MultiWindow has been removed from V3.4 as it relied on AWT implementation details. Processing 3.x is now platform agnostic so if we re-introduce the multiSketch package we will need to use a new approach.
